export class Datum {
    docdetid: number;
    docdet_fname: string;
    docdet_lname: string;
    docdet_contact: string;
    docdet_postadd : string;
    docdet_email : string;
    docdet_status: string;
    docdet_imageurl:string;
    login_loginid: number;
    docdet_lang:string;
    docdet_fees:number;
    docdet_qualify_1:string;
    docdet_qualify_2:string;
    docdet_qualify_3:string;
    docdet_city:string;
    docdet_exp:string;
    docdet_special:string;
    docdet_licnumber:string;
    docdet_clinicloc:string;
    docdet_qual1_det:string;
    docdet_qual2_det:string;
    docdet_qual3_det:string;
    docdet_cfees:number;
    docdet_hfees:string;
    docdet_notes:string;
    docdet_title:string;
    docdet_age:string;
    docdet_aadhar:string;
    docdet_pan:string;
    docdet_sex:string;
    docdet_licvalid:string;
    docdet_about:string;
  }  